-- filename: @C:/Pack/Branch/geili11\Content/Script/Datas\GameFlowChannelResponses.lua
-- version: lua54
-- line: [0, 0] id: 0
return ((DataMgr and {}).ReadOnly and function(r0_1, r1_1)
  -- line: [2, 2] id: 1
  return r1_1
end)("GameFlowChannelResponses", {
  GetItemPage = {
    Channel = "GetItemPage",
    GetItemPage = "Block",
    GuideMain = "Block",
    ImmersiveStory = "Block",
    LevelDelivery = "Block",
    OpenSystemUI = "Ignore",
    SkillFeature = "Block",
    Sojourn = "Ignore",
    SystemGuideWithUI = "Block",
    SystemGuideWithoutUI = "Block",
  },
  GuideMain = {
    Channel = "GuideMain",
    GetItemPage = "Block",
    GuideMain = "Ignore",
    ImmersiveStory = "Block",
    LevelDelivery = "Block",
    OpenSystemUI = "Ignore",
    SkillFeature = "Block",
    Sojourn = "Block",
    SystemGuideWithUI = "Ignore",
    SystemGuideWithoutUI = "Ignore",
  },
  ImmersiveStory = {
    Channel = "ImmersiveStory",
    GetItemPage = "Block",
    GuideMain = "Block",
    ImmersiveStory = "Block",
    LevelDelivery = "Block",
    OpenSystemUI = "Block",
    SkillFeature = "Block",
    Sojourn = "Ignore",
    SystemGuideWithUI = "Ignore",
    SystemGuideWithoutUI = "Block",
  },
  LevelDelivery = {
    Channel = "LevelDelivery",
    GetItemPage = "Block",
    GuideMain = "Block",
    ImmersiveStory = "Block",
    LevelDelivery = "Block",
    OpenSystemUI = "Block",
    SkillFeature = "Block",
    Sojourn = "Block",
    SystemGuideWithUI = "Block",
    SystemGuideWithoutUI = "Block",
  },
  OpenSystemUI = {
    Channel = "OpenSystemUI",
    GetItemPage = "Ignore",
    GuideMain = "Ignore",
    ImmersiveStory = "Block",
    LevelDelivery = "Block",
    OpenSystemUI = "Ignore",
    SkillFeature = "Ignore",
    Sojourn = "Ignore",
    SystemGuideWithUI = "Ignore",
    SystemGuideWithoutUI = "Ignore",
  },
  SkillFeature = {
    Channel = "SkillFeature",
    GetItemPage = "Block",
    GuideMain = "Block",
    ImmersiveStory = "Block",
    LevelDelivery = "Block",
    OpenSystemUI = "Ignore",
    SkillFeature = "Block",
    Sojourn = "Ignore",
    SystemGuideWithUI = "Block",
    SystemGuideWithoutUI = "Block",
  },
  Sojourn = {
    Channel = "Sojourn",
    GetItemPage = "Ignore",
    GuideMain = "Block",
    ImmersiveStory = "Ignore",
    LevelDelivery = "Block",
    OpenSystemUI = "Ignore",
    SkillFeature = "Ignore",
    Sojourn = "Ignore",
    SystemGuideWithUI = "Block",
    SystemGuideWithoutUI = "Block",
  },
  SystemGuideWithUI = {
    Channel = "SystemGuideWithUI",
    GetItemPage = "Block",
    GuideMain = "Ignore",
    ImmersiveStory = "Ignore",
    LevelDelivery = "Block",
    OpenSystemUI = "Ignore",
    SkillFeature = "Block",
    Sojourn = "Block",
    SystemGuideWithUI = "Block",
    SystemGuideWithoutUI = "Block",
  },
  SystemGuideWithoutUI = {
    Channel = "SystemGuideWithoutUI",
    GetItemPage = "Block",
    GuideMain = "Ignore",
    ImmersiveStory = "Block",
    LevelDelivery = "Block",
    OpenSystemUI = "Block",
    SkillFeature = "Block",
    Sojourn = "Block",
    SystemGuideWithUI = "Block",
    SystemGuideWithoutUI = "Block",
  },
})
